### PR TITLE
Add NixOS support through Flakes

### LINKED ISSUE #302: Include Cargo.lock for cargo-bpf
Thank you for the great project, I'm very excited to use it.

I'm currently trying to package `cargo bpf` for NixOS, which assumes that upstream will provide a Cargo.lock file, so I'm not able to easily package it. I can generate it myself but would prefer that it lives upstream.

(AFAIK it is considered best practice to provide a working Cargo.lock file in the repository for binaries.)

### PR DESCRIPTION
**Pull request by rsdy**
This needs more testing, but basics work.

Closes #302.

CC: @djahandarie Please review, and test if you have a moment!

### CODE REVIEW

**Comment by rsdy** [comment]
Currently I'm trying to get `nix build` working, but it seems like there's an issue with submodules from what I can tell.

**Comment by djahandarie** [comment]
Wow, I didn't expect you to try and fully package it, thank you! This is how I successfully packaged it:
```nix
buildInputs = with pkgs; [
          libelf
          zlib
          llvm_13
          llvm_13.dev
          llvmPackages_13.libclang
          libbpf
          libbfd
          libxml2
          glibc
        ];
        nativeBuildInputs = with pkgs; [
          pkg-config
          rustPlatform.bindgenHook
        ];
```
(the `bindgenHook` takes care of setting most of the nix vars).

Where I gave up was trying to make it build on musl...

**Comment by rsdy** [comment]
Wow, this is useful, thanks! I don't think musl is a good idea on Nix, unless you have a specific use case?

**Comment by rsdy** [comment]
Eh I still can't get `nix build` to complete due to some linking errors. I have no idea what's missing...

**Pull request merged**
