### PR TITLE
fpic flag

### PR DESCRIPTION
**Pull request by sebastiaoamaro**
Added fpic flag to the build of "bpf-sys", related to issue #189.

### CODE REVIEW

**Comment by rhdxmr** [comment]
@sebastiaoamaro 

Thank you for your contribution.

Please commit your code with `Signed-off-by` trailer.
You can do that by `git commit -s`.
And then re-push your branch with force option.


And it's vague to me what happens if both `-fPIE` and `-fPIC` are specified. So I
think specifying only `-fPIC` is enough.

By compiling with `-fPIC`, the resulting relocatable file can be linked into
PIE executables and shared libraries.

How do you think about replacing `-fPIE` with `-fPIC`? Not just appending
`-fPIC`.

**Comment by sebastiaoamaro** [comment]
I am not an expert in the matter, but after reading the description it makes sense to me to replace -fPIE with -fPIC. I committed the change to this branch https://github.com/sebastiaoamaro/redbpf/tree/fpic-flag

**Comment by rhdxmr** [comment]
@sebastiaoamaro 
Could you do this in your main branch?
1. `git reset HEAD^`. To reset right before the first commit
2. Just remove `-fPIE`
3. `git commit -s`. To commit with signature.
4. `git push -f`. To push main branch forcibly.

I will be able to merge this PR after you do this tasks.

**Comment by sebastiaoamaro** [comment]
Never did a pull request before, Thanks for the patience :) Think it is done now? I hope...

**Comment by rhdxmr** [comment]
Yeah, this is what I expected.
I'm approving this and build-test will start. I hope all build tests succeed.

**Review by rhdxmr — APPROVED** [review]

**Pull request merged**
